MOCK_EVENTS = [
    {
        "id": 100001,
        "title": "TypeScript Conference 2026",
        "catch": "TypeScriptの最新動向を学ぶカンファレンス",
        "description": "TypeScript 6.0の新機能やエコシステムの最新動向について、国内外のスピーカーが登壇します。型システムの進化、パフォーマンス改善、大規模プロジェクトでの活用事例など、幅広いトピックを扱います。",
        "url": "https://connpass.com/event/100001/",
        "image_url": None,
        "hash_tag": "tsconf2026",
        "started_at": "2026-03-15T10:00:00+09:00",
        "ended_at": "2026-03-15T18:00:00+09:00",
        "limit": 200,
        "event_type": "participation",
        "open_status": "open",
        "group": {"id": 1, "subdomain": "tsconf", "title": "TypeScript Japan", "url": "https://tsconf.connpass.com/"},
        "address": "東京都渋谷区渋谷2-21-1",
        "place": "渋谷ヒカリエ ホールA",
        "lat": "35.6590",
        "lon": "139.7034",
        "owner_id": 1001,
        "owner_nickname": "ts_organizer",
        "owner_display_name": "TypeScript Japan運営",
        "accepted": 150,
        "waiting": 20,
        "updated_at": "2026-02-01T10:00:00+09:00",
    },
    {
        "id": 100002,
        "title": "Python機械学習もくもく会 #42",
        "catch": "Pythonで機械学習を学ぼう",
        "description": "機械学習に興味があるエンジニアが集まり、もくもくと学習・開発を進める会です。初心者歓迎。scikit-learn、PyTorch、TensorFlowなど、お好きなライブラリで取り組めます。",
        "url": "https://connpass.com/event/100002/",
        "image_url": None,
        "hash_tag": "pyml_mokumoku",
        "started_at": "2026-03-20T19:00:00+09:00",
        "ended_at": "2026-03-20T21:00:00+09:00",
        "limit": 30,
        "event_type": "participation",
        "open_status": "open",
        "group": {"id": 2, "subdomain": "pyml", "title": "Python ML Study", "url": "https://pyml.connpass.com/"},
        "address": "東京都港区六本木3-2-1",
        "place": "六本木コワーキングスペース",
        "lat": "35.6627",
        "lon": "139.7320",
        "owner_id": 1002,
        "owner_nickname": "ml_master",
        "owner_display_name": "ML太郎",
        "accepted": 25,
        "waiting": 3,
        "updated_at": "2026-02-05T12:00:00+09:00",
    },
    {
        "id": 100003,
        "title": "React/Next.js 最新アップデート解説 LT会",
        "catch": "React 20とNext.js 16の新機能をLTで紹介",
        "description": "React 20とNext.js 16のリリースに伴い、新機能や変更点をLT形式で共有します。Server Components、Partial Prerendering、Turbopackの改善など、フロントエンド開発者必見の内容です。",
        "url": "https://connpass.com/event/100003/",
        "image_url": None,
        "hash_tag": "react_nextjs_lt",
        "started_at": "2026-03-22T14:00:00+09:00",
        "ended_at": "2026-03-22T17:00:00+09:00",
        "limit": 80,
        "event_type": "participation",
        "open_status": "open",
        "group": {"id": 3, "subdomain": "react-jp", "title": "React Japan User Group", "url": "https://react-jp.connpass.com/"},
        "address": None,
        "place": "オンライン (Zoom)",
        "lat": None,
        "lon": None,
        "owner_id": 1003,
        "owner_nickname": "react_lover",
        "owner_display_name": "React大好きエンジニア",
        "accepted": 60,
        "waiting": 0,
        "updated_at": "2026-02-03T09:00:00+09:00",
    },
    {
        "id": 100004,
        "title": "クラウドネイティブ Days Tokyo 2026",
        "catch": "Kubernetes、サーバーレス、マイクロサービスの祭典",
        "description": "クラウドネイティブ技術に関する国内最大級のカンファレンスです。Kubernetes、Istio、Argo CD、AWS Lambda、CloudFlare Workersなど、最新のクラウドネイティブ技術のセッションが満載です。",
        "url": "https://connpass.com/event/100004/",
        "image_url": None,
        "hash_tag": "cndt2026",
        "started_at": "2026-04-10T09:30:00+09:00",
        "ended_at": "2026-04-11T18:00:00+09:00",
        "limit": 500,
        "event_type": "participation",
        "open_status": "open",
        "group": {"id": 4, "subdomain": "cndtokyo", "title": "CloudNative Days Committee", "url": "https://cndtokyo.connpass.com/"},
        "address": "東京都江東区有明3-11-1",
        "place": "東京ビッグサイト 会議棟",
        "lat": "35.6298",
        "lon": "139.7946",
        "owner_id": 1004,
        "owner_nickname": "cloud_native",
        "owner_display_name": "CNDT実行委員会",
        "accepted": 380,
        "waiting": 45,
        "updated_at": "2026-02-06T15:00:00+09:00",
    },
    {
        "id": 100005,
        "title": "仕様駆動開発ワークショップ - Spec-Driven Developmentを体験しよう",
        "catch": "AIと仕様駆動で開発プロセスを革新",
        "description": "仕様駆動開発（Spec-Driven Development）の基本概念からハンズオンまでを一日で学ぶワークショップです。要件定義から設計、タスク分解、TDD実装まで、AIエージェントを活用した開発フローを実践します。",
        "url": "https://connpass.com/event/100005/",
        "image_url": None,
        "hash_tag": "sdd_workshop",
        "started_at": "2026-03-29T10:00:00+09:00",
        "ended_at": "2026-03-29T17:00:00+09:00",
        "limit": 40,
        "event_type": "participation",
        "open_status": "open",
        "group": {"id": 5, "subdomain": "ai-dev", "title": "AI-Driven Development Community", "url": "https://ai-dev.connpass.com/"},
        "address": "東京都千代田区丸の内1-9-2",
        "place": "グラントウキョウサウスタワー セミナールーム",
        "lat": "35.6785",
        "lon": "139.7680",
        "owner_id": 1005,
        "owner_nickname": "spec_driven",
        "owner_display_name": "SDD推進委員会",
        "accepted": 35,
        "waiting": 8,
        "updated_at": "2026-02-04T11:00:00+09:00",
    },
    {
        "id": 100006,
        "title": "Go言語 パフォーマンスチューニング入門",
        "catch": "Goアプリケーションの高速化テクニック",
        "description": "Go言語のパフォーマンスチューニングについて、プロファイリングツールの使い方から、メモリ管理、並行処理の最適化、データベースアクセスの改善まで解説します。",
        "url": "https://connpass.com/event/100006/",
        "image_url": None,
        "hash_tag": "go_perf",
        "started_at": "2026-04-05T13:00:00+09:00",
        "ended_at": "2026-04-05T17:00:00+09:00",
        "limit": 50,
        "event_type": "participation",
        "open_status": "open",
        "group": {"id": 6, "subdomain": "go-tokyo", "title": "Go Tokyo", "url": "https://go-tokyo.connpass.com/"},
        "address": "東京都新宿区西新宿2-8-1",
        "place": "都庁前コワーキングスペース",
        "lat": "35.6896",
        "lon": "139.6917",
        "owner_id": 1006,
        "owner_nickname": "gopher",
        "owner_display_name": "Go太郎",
        "accepted": 40,
        "waiting": 0,
        "updated_at": "2026-02-02T14:00:00+09:00",
    },
    {
        "id": 100007,
        "title": "AWS re:Boot Meetup - re:Invent 2025 振り返り",
        "catch": "re:Invent 2025の注目アップデートを総まとめ",
        "description": "AWS re:Invent 2025で発表された新サービスやアップデートを振り返ります。Amazon Bedrock AgentCore、Aurora DSQL、S3 Tablesなど、注目のサービスを実際に触ってみた感想を共有します。",
        "url": "https://connpass.com/event/100007/",
        "image_url": None,
        "hash_tag": "aws_reboot",
        "started_at": "2026-03-08T14:00:00+09:00",
        "ended_at": "2026-03-08T17:00:00+09:00",
        "limit": 100,
        "event_type": "participation",
        "open_status": "open",
        "group": {"id": 7, "subdomain": "jaws-ug", "title": "JAWS-UG 東京", "url": "https://jaws-ug.connpass.com/"},
        "address": "東京都目黒区下目黒1-8-1",
        "place": "Amazon Japan目黒オフィス",
        "lat": "35.6329",
        "lon": "139.7152",
        "owner_id": 1007,
        "owner_nickname": "jawsug_admin",
        "owner_display_name": "JAWS-UG運営",
        "accepted": 85,
        "waiting": 10,
        "updated_at": "2026-02-06T08:00:00+09:00",
    },
    {
        "id": 100008,
        "title": "Rust初心者ハンズオン - ゼロから始めるRust",
        "catch": "Rustの基礎を一緒に学びましょう",
        "description": "Rust初心者向けのハンズオンイベントです。所有権、借用、ライフタイムなどRust固有の概念を、簡単なCLIツール作成を通じて学びます。事前知識は不要です。",
        "url": "https://connpass.com/event/100008/",
        "image_url": None,
        "hash_tag": "rust_beginners",
        "started_at": "2026-04-12T10:00:00+09:00",
        "ended_at": "2026-04-12T16:00:00+09:00",
        "limit": 25,
        "event_type": "participation",
        "open_status": "open",
        "group": {"id": 8, "subdomain": "rust-jp", "title": "Rust Japan", "url": "https://rust-jp.connpass.com/"},
        "address": "大阪府大阪市北区梅田1-2-2",
        "place": "大阪駅前第2ビル セミナーホール",
        "lat": "34.7003",
        "lon": "135.4968",
        "owner_id": 1008,
        "owner_nickname": "rustacean",
        "owner_display_name": "Rust Japan運営",
        "accepted": 20,
        "waiting": 2,
        "updated_at": "2026-02-05T16:00:00+09:00",
    },
    {
        "id": 100009,
        "title": "デザインシステム構築 実践カンファレンス",
        "catch": "企業のデザインシステム構築事例を共有",
        "description": "デザインシステムの構築・運用に関するカンファレンスです。Figma連携、コンポーネントライブラリの設計、アクセシビリティ対応、デザイントークンの管理など、実践的な事例を紹介します。",
        "url": "https://connpass.com/event/100009/",
        "image_url": None,
        "hash_tag": "design_system_conf",
        "started_at": "2026-04-18T13:00:00+09:00",
        "ended_at": "2026-04-18T18:00:00+09:00",
        "limit": 120,
        "event_type": "participation",
        "open_status": "open",
        "group": {"id": 9, "subdomain": "design-system", "title": "Design System Community", "url": "https://design-system.connpass.com/"},
        "address": None,
        "place": "オンライン (YouTube Live)",
        "lat": None,
        "lon": None,
        "owner_id": 1009,
        "owner_nickname": "ds_organizer",
        "owner_display_name": "デザインシステムコミュニティ",
        "accepted": 95,
        "waiting": 0,
        "updated_at": "2026-02-07T10:00:00+09:00",
    },
    {
        "id": 100010,
        "title": "セキュリティエンジニア勉強会 - OWASP Top 10 2025対策",
        "catch": "最新のWebセキュリティ脅威と対策を学ぶ",
        "description": "OWASP Top 10 2025に基づく最新のWebアプリケーションセキュリティについて学びます。AIを活用した脆弱性検出、サプライチェーンセキュリティ、APIセキュリティなど、最新トレンドをカバーします。",
        "url": "https://connpass.com/event/100010/",
        "image_url": None,
        "hash_tag": "sec_study",
        "started_at": "2026-03-25T19:00:00+09:00",
        "ended_at": "2026-03-25T21:30:00+09:00",
        "limit": 60,
        "event_type": "participation",
        "open_status": "open",
        "group": {"id": 10, "subdomain": "sec-study", "title": "Security Study Group", "url": "https://sec-study.connpass.com/"},
        "address": "東京都品川区東品川2-2-4",
        "place": "天王洲セントラルタワー 会議室",
        "lat": "35.6234",
        "lon": "139.7487",
        "owner_id": 1010,
        "owner_nickname": "sec_master",
        "owner_display_name": "セキュリティ勉強会運営",
        "accepted": 45,
        "waiting": 5,
        "updated_at": "2026-02-04T13:00:00+09:00",
    },
]
